/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex7;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.*;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author ierimaruxi
 */


public class Server_JFrame extends javax.swing.JFrame {
     ArrayList<CarAccess> list = new ArrayList<>();
    public Server_JFrame() {
        initComponents();
    }
            
    //GUI
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listOfCars = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listOfCars.setColumns(20);
        listOfCars.setRows(5);
        jScrollPane1.setViewportView(listOfCars);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cars from Parking:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // GUI ENDED
    
    public String handlePlateNumberRequest(String plateNumber){
        CarAccess carAccess = new CarAccess(plateNumber,System.currentTimeMillis());
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(CarAccess.class.getName()).log(Level.SEVERE, null, ex);
        }
        String message="";
        // verificam daca nr exista deja
        if (carAccess.verifyCar(list, plateNumber)){
            //daca exista 
            //calculez timpul de stationare
            long time = System.currentTimeMillis() - carAccess.getAccessTime(); 
            //sterg numarul din lista 
            list.remove(carAccess);
           
            //returnez un sir "numar_inmatriculare pret XX RON"
            message="Plate number:"+ plateNumber + " deleted, price: "+time + " RON";
            return message;
        }
        else{
            // daca nu exista il adaug in lista
            list.add(carAccess);
            //returnez un sir "numaru_inmatriculare inregistrat"
            message="Plate number "+ plateNumber+ " registred";
            
            return message;
        }
        
    }
    
    void startServer() throws IOException{
        //....
        ServerSocket ss =new ServerSocket(4050);

        while(true){
            System.out.println("Astept conexiune de la client...");
            Socket s = ss.accept(); //metoda blocanta
            System.out.println("Clientul s-a conectat!");
            //...... 
            BufferedReader fluxIn = new BufferedReader(new InputStreamReader(s.getInputStream()));
            PrintWriter fluxOut = new PrintWriter(new OutputStreamWriter(s.getOutputStream()),true);
            //......
            String line = "";
            while(!line.equals("close connection")){
                //citesc nr inmatriculare
                line = fluxIn.readLine();
                System.out.println("Am primti de la client numarul de inmatriculare: " + line);
                String carPlateNumber =line;
       
                //apelez metoda handle plate number
                 String response= handlePlateNumberRequest(carPlateNumber);
                 
                 // afisez masinile din parcare in interfata
                 for(CarAccess car: list){
                    listOfCars.append(car.getPlateNumber());
                    listOfCars.append("\n");
           }
                //returnez catre client rezultatul 
                fluxOut.println(response);
            }
              
            s.close();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_JFrame().setVisible(true);
            }
        });
        
       Server_JFrame s = new Server_JFrame();
       s.startServer();
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listOfCars;
    // End of variables declaration//GEN-END:variables
}
